version: 2.1

executors:
  node_executor:
    docker:
      - image: cimg/node:17.1.0

jobs:
  install:
    executor: node_executor
    steps:
      - checkout
      - run:
          name: "Install our react app deps"
          command: npm install
      - save_cache:
          key: v1-npm-packages
          paths:
            - ./node_modules
  
  test:
    executor: node_executor
    steps:
      - checkout
      - restore_cache:
          key: v1-npm-packages
      - run: npm run test -- --watchAll=false
  
  analyze:
    executor: node_executor
    steps:
      - checkout
      - restore_cache:
          key: v1-npm-packages
      - run: npm audit

workflows:
  workflow:
    jobs:
      - install
      - test:
          requires:
            - install
      - analyze:
          requires:
            - test
            