version: 2.1

executors:
  node_executor:
    docker:
      - image: cimg/node:17.1.0

commands:
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

jobs:
  save_hello_world:
    executor: node_executor
    steps:
      - run:
          name: "Save hello world to output.txt"
          command: echo "Hello, World" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  
  print_ouptut_file:
    executor: node_executor
    steps:
      - attach_workspace:
          at: ~/
      - print_pipeline_id 
      - run:
          name: "Print from output file"
          command: cat ~/output.txt
      - run: return 1
      - run:
          command: echo "You're job failed! Haha!"
          when: on_fail

workflows:
  workflow:
    jobs:
      - save_hello_world
      - print_ouptut_file:
          requires:
            - save_hello_world
            