version: 2.1

executors:
  node_executor:
    docker:
      - image: cimg/node:17.1.0

jobs:
  print_hello:
    executor: node_executor
    steps:
      - checkout
      - run:
          name: "Print hello"
          command: "echo Hello"
  
  print_world:
    executor: node_executor
    steps:
      - checkout
      - run:
          name: "Print world"
          command: "echo World!"

workflows:
  say-hello-workflow:
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
