version: 2.1

jobs:
  save_hello_world:
    docker:
      - image: cimg/base:2021.11
    steps:
      - run:
          name: "Save hello world to output.txt"
          command: echo "Hello, World" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  
  print_ouptut_file:
    docker:
      - image: cimg/base:2021.11
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: "Print from output file"
          command: cat ~/output.txt   

workflows:
  workflow:
    jobs:
      - save_hello_world
      - print_ouptut_file:
          requires:
            - save_hello_world