version: 2.1

executors:
  node_executor:
    docker:
      - image: cimg/node:17.1.0

commands:
  # Exercise - Rollback
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          # ${CIRCLE_WORKFLOW_ID} is a Built-in environment variable 
          # ${CIRCLE_WORKFLOW_ID:0:5} takes the first 5 chars of the variable CIRCLE_CI_WORKFLOW_ID 
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name udacity-udapeople-${CIRCLE_WORKFLOW_ID:0:5}

jobs:
  install:
    executor: node_executor
    steps:
      - checkout
      - run:
          name: "Install our react app deps"
          command: npm install
      - save_cache:
          key: v1-npm-packages
          paths:
            - ./node_modules
  
  test:
    executor: node_executor
    steps:
      - checkout
      - restore_cache:
          key: v1-npm-packages
      - run: npm run test -- --watchAll=false

  create_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation deploy \
                --template-file cfn-template.yml \
                --stack-name udacity-udapeople-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1
        - run: 
            name: "create inventory file"
            command: echo "[all]" > inventory
        - run:
            name: "add ip to inventory file"
            command: |
              aws cloudformation \
                --region us-east-1 \
                describe-stacks \
                --stack-name udacity-udapeople-${CIRCLE_WORKFLOW_ID:0:5} \
                --query "Stacks[0].Outputs[?OutputKey=='ec2PublicIP'].OutputValue" \
                --output text >> inventory
        - persist_to_workspace:
            root: .
            paths:
              - inventory
        - destroy_environment
  
  configure_infrastructure:
    docker: 
      - image: cimg/python:3.10.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints: ["a8:a3:cf:6f:38:04:c3:5c:8e:0a:70:ca:d8:77:11:68"]
      - run:
          name: "install ansible deps"
          command: pip install ansible
      - run:
          name: "configure server"
          command: ansible-playbook -i inventory playbook.yml

workflows:
  workflow:
    jobs:
      # - install
      # - test:
      #     requires:
      #       - install
      - create_infrastructure:
          # requires:
          #   - test
          filters:
            branches:
              only:
                - "main"
      - configure_infrastructure:
          requires:
            - create_infrastructure
          filters:
            branches:
              only:
                - "main"  