---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "remove uneeded deps"
  become: yes
  apt:
    autoremove: yes

- name: "setup prometheus user + needed folders"
  shell: |
    useradd --no-create-home prometheus
    mkdir /etc/prometheus
    mkdir /var/lib/prometheus

- name: "download and untar our prometheus.tar.gz file into the proper directory"
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v2.31.1/prometheus-2.31.1.linux-amd64.tar.gz"
    dest: ~/prometheus
    remote_src: yes

- name: "move prometheus files where they need to go"
  shell: |
    cp ~/prometheus/prometheus /usr/local/bin
    cp ~/prometheus/promtool /usr/local/bin/
    cp -r ~/prometheus/consoles /etc/prometheus
    cp -r ~/prometheus/console_libraries /etc/prometheus
    cp ~/prometheus/promtool /usr/local/bin/

- name: "change prometheus permissions as needed"
  shell: |
    chown prometheus:prometheus /etc/prometheus
    chown prometheus:prometheus /usr/local/bin/prometheus
    chown prometheus:prometheus /usr/local/bin/promtool
    chown -R prometheus:prometheus /etc/prometheus/consoles
    chown -R prometheus:prometheus /etc/prometheus/console_libraries
    chown -R prometheus:prometheus /var/lib/prometheus

- name: "start prometheus service"
  shell: |
    systemctl daemon-reload
    systemctl enable prometheus