---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "remove uneeded deps"
  become: yes
  apt:
    autoremove: yes

- name: "setup prometheus user + needed folders"
  shell: |
    useradd --no-create-home prometheus
    mkdir /etc/prometheus
    mkdir /var/lib/prometheus

- name: "ensure ~/prometheus dir exists"
  file:
    path: "~/prometheus"
    state: directory
    mode: 0755

- name: "download and untar our prometheus.tar.gz file into the proper directory"
  shell: |
    wget https://github.com/prometheus/prometheus/releases/download/v2.31.1/prometheus-2.31.1.linux-amd64.tar.gz
    tar xvfz prometheus-*.*-amd64.tar.gz
    mv prometheus-*.*-amd64 prometheus

- name: "copy our prometheus.service file into the correct directory"
  template: 
    src: "files/prometheus.service"
    dest: "/etc/systemd/system/prometheus.service"

- name: "ls our prometheus directory"
  shell: ls ~/prometheus

- name: "move prometheus files where they need to go"
  shell: |
    cp prometheus/prometheus /usr/local/bin/
    cp prometheus/promtool /usr/local/bin/
    cp -r prometheus/consoles /etc/prometheus
    cp -r prometheus/console_libraries /etc/prometheus

- name: "copy our prometheus.yml file into the correct directory"
  template: 
    src: "files/prometheus.yml"
    dest: "/etc/prometheus"
    force: yes

- name: "get our nodejs ec2 public dns name and input into prometheus file"
  ansible.builtin.replace:
    path: "/etc/prometheus/prometheus.yml"
    regexp: "^nodejsEC2PublicDNS$"
    replace: "{{ item }}"
  debug:
    msg: "{{ item }}"
  with_inventory_hostnames:
    - nodejs

- name: "ensure /etc/systemd/system dir exists"
  file:
    path: "/etc/systemd/system"
    state: directory
    mode: 0755

- name: "copy our prometheus.service file into the correct directory"
  template: 
    src: "files/prometheus.service"
    dest: "/etc/systemd/system/prometheus.service"

- name: "change prometheus permissions as needed"
  shell: |
    chown prometheus:prometheus /etc/prometheus
    chown prometheus:prometheus /usr/local/bin/prometheus
    chown prometheus:prometheus /usr/local/bin/promtool
    chown -R prometheus:prometheus /etc/prometheus/consoles
    chown -R prometheus:prometheus /etc/prometheus/console_libraries
    chown -R prometheus:prometheus /var/lib/prometheus

- name: "start prometheus service"
  shell: |
    systemctl daemon-reload
    systemctl enable prometheus
    systemctl start prometheus
    systemctl status prometheus