---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "remove uneeded deps"
  become: yes
  apt:
    autoremove: yes

- name: "grab nodejs from nodesource"
  shell: "curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -"

- name: "install NodeJS and NPM using apt"
  apt: 
    name: "nodejs"
    state: present # default

- name: "install pm2 using npm"
  npm:
    name: "pm2"
    state: present # default
    global: yes

- name: "ensure web dir exists"
  file:
    path: "~/web"
    state: directory
    mode: 0755

- name: "copy our test index page to our web dir"
  template: 
    src: "files/index.js"
    dest: "~/web/index.js"

- name: "start up nodejs server using pm2"
  shell: "pm2 start ~/web/index.js -f"